# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b15f048517c58b60842823165d220ce126b686bf28e3cd5caeea014b3e6cef1ed39b95724b4366e563e06c33af125e571c4a7b0e423721510a03b2cf268bb071

test:
  secret_key_base: 7da31d86d43dec9f4f68b47467bdaa32b08ed95474f2c40db81bc08776d7c41561d240c757b4c8fda9523e37f549c544aea89c4d79a3dee8de8b3ecc758a9031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
